### ISSUE TITLE
Can you please add an option to enter address and phone number.

### ISSUE THREAD

**Issue by tushar0837** [iodigital-com/SecretSanta#560] opened 2022-12-15 13:16 UTC
As most of the parties are virtual now. Can you please add an option to enter address and phone number so that assigned person can deliver a gift to them. RIght now we are addind them to wishlist but its hard to manage, We have to go to every wishlist and check if phone and address is entered or not. Would be a simple 1.

**Comment by tvlooy** [comment] 2022-12-15 13:19
If it's a simple one, you might want to give it a go then. Looking forward to your MR

**Comment by TomCan** [comment] 2022-12-15 13:35
Duplicate of #535

**Closed** 2022-12-15 13:36 UTC
